site_name: Research Graph Augment API
site_description: Augment API Documentation
repo_url: https://github.com/researchgraph/augment-api-beta/
theme:
  name: material
nav:
- Introduction: index.md
- Reference: reference.md
- Example Notebooks: 
    - Fetch metadata for ORCID ID: notebooks/orcid.ipynb
    - Fetch metadata for DOI: notebooks/doi.ipynb

plugins:
  - mkdocs-jupyter
  - search