site_name: Augment API
site_description: Augment API Documentation
repo_url: https://github.com/researchgraph/augment-api-beta/
theme:
  name: material
nav:
- Home: index.md
- Reference: reference.md
- Example Notebooks: notebooks/base.ipynb

plugins:
  - mkdocs-jupyter
  - search